# gh search commits --hash 272effd --repo dgatf/msrc

name: CI - MSRC firmware

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - board/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get actions code
        uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Git tags
        run: git fetch --prune --unshallow

      - name: Build firmware
        uses: samyarsadat/Pico-Build-Action@v1
        with:
          source_dir: "board"
          output_dir: "../build"
          cmake_args: "-DCMAKE_BUILD_TYPE=Release"
        
      - name: Upload to Google Drive
        uses: logickoder/g-drive-upload@main
        with:
          credentials: ${{ secrets.GOOGLE_ID }}
          filename: 'build/project/MSRC-RP2040.uf2'
          folderId: ${{ secrets.FOLDER_ID }}
          overwrite: 'true'
          name: MSRC-RP2040_xdfly.uf2
