name: CI - MSRC Link

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - msrc_gui/**

jobs:
  linux:
    runs-on: ubuntu-22.04

    steps:
      - name: Get actions code
        uses: actions/checkout@v4
        
      - name: Install QT
        uses: jurplel/install-qt-action@v2
        
      - name: Git tags
        run: git fetch --prune --unshallow

      - name: Build
        run: |
          mkdir build
          cd build
          qmake ../msrc_gui
          make
          
      - name: Install LinuxDeploy
        run: |
          cd msrc_gui
          wget https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage
          sudo chmod +x linuxdeployqt-continuous-x86_64.AppImage
      
      - name: Install fuse
        run: sudo apt install libfuse2

      - name: Create AppImage
        run: |
          cp build/msrc_gui msrc_gui/appdir
          cd msrc_gui/appdir
          ../linuxdeployqt-continuous-x86_64.AppImage msrc_gui -appimage
          mv *.AppImage msrc_gui.AppImage

      - name: Upload to Google Drive
        uses: logickoder/g-drive-upload@main
        with:
          credentials: ${{ secrets.GOOGLE_ID }}
          filename: 'msrc_gui/appdir/msrc_gui.AppImage'
          folderId: ${{ secrets.FOLDER_ID }}
          overwrite: 'true'
          name: msrc_link_xdfly.AppImage

  macos:
    runs-on: macos-14

    steps:
      - name: Get actions code
        uses: actions/checkout@v4
        
      - name: Install QT
        uses: jurplel/install-qt-action@v4
        with:
          version: '5.15.2'
        
      - name: Git tags
        run: git fetch --prune --unshallow
      
      - name: Build
        run: |
          mkdir build
          cd build
          qmake ../msrc_gui
          make
          macdeployqt msrc_gui.app -dmg
        
      - name: Upload to Google Drive
        uses: logickoder/g-drive-upload@main
        with:
          credentials: ${{ secrets.GOOGLE_ID }}
          filename: 'build/msrc_gui.dmg'
          folderId: ${{ secrets.FOLDER_ID }}
          overwrite: 'true'
          name: msrc_link_xdfly.dmg

  windows:
    runs-on: windows-2019

    steps:
      - name: Get actions code
        uses: actions/checkout@v4
        
      - name: install qt static
        uses: orestonce/install-qt-static@v0.4.3
        with:
          version: Qt5.15.7-Windows-x86_64-MinGW8.1.0-staticFull-20221104

      - name: Git tags
        run: git fetch --prune --unshallow
        
      - name: Build  
        run: |
          mkdir build
          cd build
          qmake ../msrc_gui
          make
          mingw32-make release

      - name: Upload to Google Drive
        uses: logickoder/g-drive-upload@main
        with:
          credentials: ${{ secrets.GOOGLE_ID }}
          filename: 'build/release/msrc_gui.exe'
          folderId: ${{ secrets.FOLDER_ID }}
          overwrite: 'true'
          name: msrc_link_xdfly.exe
